blog/urls.py
# blog/urls.py
from django.conf.urls import url
from . import views
from . import views_cbv

urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
    url(r'^(?P<id>\d+)/$', views.post_detail, name='post_detail'),
    url(r'^new/$', views.post_new, name='post_new'),
    url(r'^(?P<id>\d+)/edit/$', views.post_edit, name='post_edit'),
    url(r'^comments/$', views.comment_list, name='comment_list'),
    url(r'^cbv/new/$', views_cbv.post_new),
]

travel/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.shortcuts import redirect
from django.conf.urls.static import static
# def root(request):
#     return redirect('blog:post_list')

urlpatterns = [
    # url(r'^$', root, name='root'),
    url(r'^$', lambda r: redirect('blog:post_list'), name='root'), # root 함수 이용해서 url(r'^$', root, name='root') 로 개발하는것과 같은 효과. lambda 이용.
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace='blog')), # namespace 를 지정해주므로써 다른 앱의 동일한 url name을 구분 지을수 있다. blog:post_list , shop:post_list   include에 대한 namaspace이므로 헷갈리지 말것.
    url(r'^dojo/', include('dojo.urls', namespace='dojo')),
    # url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^accounts/', include('accounts.urls')), # auth와 연동해서 쓸때에는 namespace연동 노노
    url(r'^accounts/', include('allauth.urls')), # sns login
    url(r'^shop/', include('shop.urls', namespace='shop')),
]

# MEDIA_URL에 설정된 경로로 시작을 한다면 ROOT에 설정된 경로에서 서빙을 하겠다.
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls))
    ]

blog/models.py
# blog/models.py
import re
from django.forms import ValidationError
from django.core.urlresolvers import reverse
from django.db import models
from django.conf import settings

# [+_]?  정규표현식에서 ?는 0회 혹은 1회 출현을 의미함. 없거나 혹은 한번 나오거나. 
def lnglat_validator(value):
    if not re.match(r'^([+-]?\d+\.?\d*),([+-]?\d+\.?\d*)$', value):
        raise ValidationError('Invalid LngLat Type')

class Post(models.Model):
    STATUS_CHOICES = (
        ('d', 'Draft'),
        ('p', 'Published'),
        ('w', 'Withdrawn'),
    )

    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='blog_post_set')
    # related_name='+' -> related_name을 포기한다는 것.
    # shop모델과 related_name이 충돌나는것을 포기. 충돌나는 이름을 각각 재정의 해주거나 포기해야함.


    # author = models.CharField(max_length=20)
    title = models.CharField(max_length=100) # 길이제한이 있는 문자열
    content = models.TextField() # 길이제한이 없는 문자열
    photo = models.ImageField(blank=True, upload_to='blog/post/%Y/%m/%d')
    tags = models.CharField(
        max_length=100, 
        blank=True)
    lnglat = models.CharField(
        max_length=50, 
        blank=True, # 값이 없어도 저장됌. 필수값이 아니라는 뜻.
        help_text='경도, 위도 포맷으로 입력',
        validators=[lnglat_validator])
    status = models.CharField(max_length=1,choices=STATUS_CHOICES)  
    tag_set = models.ManyToManyField('Tag', blank=True) # 문자열로 클래스명을 지정해주면 릴레이션을 맺는 클래스가 같은 앱안에 있다고 판단함. 다른 앱의 모델과 릴레이션을 건다면 ? 'auth.Tag' 로 사용 
    created_at = models.DateTimeField(auto_now_add=True) # auto_now_add 최초생성시 자동으로 들어감.
    updated_at = models.DateTimeField(auto_now=True) # auto_now 레코드 생성시 자동으로 들어감.

    # choices
    # title1 = models.CharField(max_length=100,
    #     choices = (
    #         ('디비에 저장될 값1', 'ui에 보여질 레이블'),
    #         ('디비에 저장될 값2', 'ui에 보여질 레이블'),
    #         ('디비에 저장될 값3', 'ui에 보여질 레이블'),
    #     ))
    
    # 입력값을 좌우 공백 제거 strip 옵션

    # 쿼리내 기본정렬은 모델 내 Meta.ordering 설정에 따름.
    class Meta: 
        ordering = ['-id']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.id]) # detail 로 이동할때 유용하다. 새글을 작성하거나 수정했을때는 상세페이지를 보여주는것이 당연한 시나리오.

# 댓글모델
class Comment(models.Model):
    post = models.ForeignKey(Post)
    author = models.CharField(max_length=20)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name

blog/forms.py
# blog/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        # fields = ['title','content','tags','lnglat','status','tag_set']
        fields = '__all__'

blog/views.py
from django.http import Http404
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Comment
from django import forms
from .forms import PostForm
from django.views.generic import ListView
from django.contrib import messages



# Create your views here.
def post_list(request):

    print(request.user.is_authenticated)
    print(request.user)

    # qs = Post.objects.all()
    qs = Post.objects.prefetch_related('comment_set','tag_set').all()
    q = request.GET.get('q', '')
    # post_list = ListView.as_view(model=Post, paginate_by=10)
    if q:
        qs = qs.filter(title__icontains=q)

    return render(request, 'blog/post_list.html', {
        'post_list': qs,
        'q':q,
        # 'pagination': post_list,
    })

def post_detail(request, id):
    # 404 에러를 위한코드
    # try:
    #     post = Post.objects.get(id=id)
    # except Post.DoesNotExist:  
    #     raise Http404
    # 하지만 위 코드는 너무 번거로움

    # 위의 4줄가 같은코드, 특정 조건에 맞는 인스턴스 획득시에는 이걸 사용하도록
    post = get_object_or_404(Post, id=id)


    return render(request, 'blog/post_detail.html',{
        'post': post,
    })


    # http 200 응답
    # return HttpResponse()
    # return render()
    # return JsonResponse()

    # http 302 응답
    # return HttpResponseRedirect('/blog/)
    # return HttpResponseRedirect(url) # url reverse 
    # return redirect('blog:post_list')

    # http 404 응답
    # 1. raise Http404
    # 2. post = get_object_or_404(Post, id=100) # 없는 id 일 경우 http404 예외 발생
    # 3. HttpResponseNotFound() # 잘 안쓰는 방법

    # http 500 응답
    # 서버에서 요청처리중에 예기치못한 오류(코드오류, 설정오류) 가 발생할 경우

def post_new(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save()
            messages.success(request, '새 글이 등록되었습니다람쥐.')
            return redirect(post) # post.get_absolute_url() => post detail
    else:    
        form = PostForm()
    return render(request, 'blog/post_form.html', {
        'form':form,
    })

def post_edit(request, id):
    post = get_object_or_404(Post, id=id)

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.save()
            messages.success(request, '글을 수정하였습니다.')
            return redirect(post) # post.get_absolute_url() => post detail
    else:    
        form = PostForm(instance=post)
    return render(request, 'blog/post_form.html', {
        'form':form,
    })

def comment_list(request):
    # comment_list = Comment.objects.all()
    comment_list = Comment.objects.all().select_related('post') # 외래키, OneToOne 관계일때 쿼리갯수를 줄일수있다.
    return render(request, 'blog/comment_list.html', {
        'comment_list': comment_list,
    })

blog/templates/blog/comment_list.html
<!-- blog/templates/blog/comment_list.html -->
{% extends "blog/layout.html" %}

{% block content %}


<ul>
    {% for comment in comment_list  %}
    <li>
        {{ comment }}
        {{ comment.post }}
    </li>
    {% endfor %}
</ul>
{% endblock content %}

blog/templates/blog/layout.html
{% extends "layout.html" %}

{% block title %}
blog
{% endblock %}

blog/templates/blog/post_detail.html
{% extends "blog/layout.html" %}


{% block title %}
{{ post.title }}
{% endblock title %}



{% block content %}

<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <h2>{{post.title}}</h2>
            {% comment %} <img src="/media/{{ post.photo }}" alt="" style="width: 100%"> {% endcomment %}
            {% if post.photo %}
                <img src="{{ post.photo.url }}" alt="" style="width: 100%">
            {% endif %}
            
            {{post.content|linebreaks}}
            <hr>
            <h2>Comments</h2>
            <ul>
                {% for comment in post.comment_set.all %}
                <li>
                    {{comment.message}}
                    <small>by {{comment.author}}</small>
                    <small>at {{comment.created_at}}</small>
                </li>
                {% endfor %}
            </ul>
            <hr>
            <a href="{% url 'blog:post_list' %}" class="btn btn-primary">글 목록</a>
            <a href="{% url 'blog:post_edit' post.id %}" class="btn btn-primary">글 수정</a>
        </div>
    </div>
</div>


{% endblock content %}

blog/templates/blog/post_form.html
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        {{form.as_table}}
    </table>
    <input type="submit">
</form>

blog/templates/blog/post_list.html
{% extends "blog/layout.html" %}
    

{% block content %}




<div class="container">
    <div class="jumbotron">
        <h1>Django Template
            <sup>by AskDjango</sup>
        </h1>
        <p>여러분의 파이썬/장고 페이스메이커가 되겠습니다.</p>
        <p>
            <a class="btn btn-lg btn-primary" href="http://facebook.com/groups/askdjango">
                AskDjango 페이스북 그룹 &raquo;
            </a>
        </p>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <div class="alert alert-info">
                <ul>
                    <li>http://localhost:8000/blog/ 주소로 접속해보세요.</li>
                    <li>템플릿 경로를 blog/templates/post_list.html 경로가 아닌 blog/templates/blog/post_list.html 경로를 쓰는 것에 대한 이유는 후에 Template Loader 에서 설명합니다.</li>
                </ul>
            </div>

            <a href="{% url 'blog:post_new' %}" class="btn btn-primary pull-right">New Post</a>

            <p>
                <form action="" method="get">
                    <input type="text" name='q' value={{ q }}>
                    <input type="submit" value='검색' class="btn btn-primary">
                </form>
            </p>
            <table class="table table-hover table-bordered">
                <thead>
                    <tr>
                        <th>id</th>
                        <th>title</th>
                        <th>author</th>
                        <th>updated_at</th>
                        <th>comments</th>
                    </tr>
                </thead>
                <tbody>
                {% for post in post_list %}
                <tr>
                    <td>
                        {{post.id}}    
                    </td>
                    <td>
                        <a href="{% url 'blog:post_detail' post.id  %}">
                        {{post.title}}
                        </a>
                        {% for tag in post.tag_set.all %}
                        <div>
                            <span class="label label-info">
                            {{tag.name}}
                            </span>
                        </div>
                        {% endfor %}
                    </td>
                    <td>
                    <small>by {{post.author}}</small>
                    </td>
                    <td>
                    <small>by {{post.updated_at}}</small>
                    </td>
                    {% comment %} <td>
                        {{ post.comment_set.all }}
                        
                    </td> {% endcomment %}
                </tr>
                {% endfor %}
                </tbody>
            </table>

            {% comment %} <div class="text-center">
                {% bootstrap_pagination page_obj %}
            </div> {% endcomment %}
        </div>
    </div>
</div>



{% endblock %}